using Reusable;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Gunter.Services.Email.Renderers
{
    internal class FooterRenderer : EmailSectionRenderer
    {
        public static class StyleName
        {
            public const string Author = nameof(Author);
            public const string Paragraph = nameof(Paragraph);
            public const string hr = nameof(hr);
        }

        public FooterRenderer() : base(new Dictionary<string, string>
        {
            [StyleName.Author] = "color: #247BA0;",
            [StyleName.Paragraph] = "font-family: sans-serif; font-size: 12px; color: #A0A0A0;",
            [StyleName.hr] = "border: 0; border-bottom: 1px solid #ccc; background: #CCC"
        })
        { }

        public string Render(string name, DateTime timestamp)
        {
            var p = Html.p
            (
                "Auto-generated by {Name} ({Timestamp}) (UTC)".Format(new
                {
                    Name = Html.span(HtmlEncode(name)).style(StyleName.Author),
                    Timestamp = timestamp.ToString(CultureInfo.InvariantCulture)
                })
            ).style(StyleName.Paragraph);

            return new StringBuilder()
                .AppendLine(Html.hr().style(StyleName.hr).ToString())
                .AppendLine((string)p.ToString())
                .ToString();
        }
    }
}