using System;
using System.Collections.Generic;
using System.Globalization;
using Gunter.Data;
using Gunter.Reporting;
using Reusable.MarkupBuilder;
using Reusable.MarkupBuilder.Html;

namespace Gunter.Messaging.Emails.Renderers
{
    [CanRender(typeof(Reporting.Modules.Signature))]
    public class Signature : Renderer
    {
        public override IEnumerable<IHtmlElement> Render(IModule module, TestContext context)
        {
            var format = (FormatFunc)context.Formatter.Format;

            yield return Html
                 .Element("p", p => p
                     .@class("auto-generated-by")
                     .Append("Auto-generated by ")
                     .Element("span", span => span
                         .@class("app-name")
                         .Append(format($"{{{RuntimeVariable.Program.FullName.Name.ToString()}}}")))
                     .Append($" {DateTime.UtcNow.ToString(CultureInfo.InvariantCulture)} (UTC)"));

            //.AppendLine(Html.Element("hr", string.Empty).Style(Styles[Style.HorizonalRule]).ToHtml(MarkupFormatting.Empty, Enumerable.Empty<IMarkupVisitor>()))
        }
    }
}